name: data_management_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  google_fonts: ^6.1.0
  flutter_speed_dial: ^7.0.0
  intl: ^0.20.2
  sqflite: ^2.4.2
  # sqflite_common_ffi: ^2.3.0+2
  # sqflite_common_ffi_web: ^1.0.1+1
  path_provider: ^2.1.1
  path: ^1.9.1
  crypto: ^3.0.3

dependency_overrides:
  characters: ^1.4.1
  material_color_utilities: ^0.13.0
  meta: ^1.17.0
  test_api: ^0.7.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/LOGO1.png
